### ISSUE TITLE
yarn lint task broken

### ISSUE THREAD

**Issue by Akiyamka** [preactjs-templates/typescript#24] opened 2020-05-06 17:12 UTC
```
yarn lint
yarn run v1.22.4
$ eslint src/**/*.{js,jsx,ts,tsx}
Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.

Oops! Something went wrong! :(

ESLint: 6.8.0.

No files matching the pattern "src/**/*.jsx" were found.
Please check for typing mistakes in the pattern.

```

**Comment by RyanChristian4427** [comment] 2020-05-06 20:53
Can you mention your version of Node please, and have you made any edits to the template?

An unedited template works on my system, with yarn v1.22.4 and node v13.13.0.

**Comment by Akiyamka** [comment] 2020-05-07 07:27
> Can you provide your version of Node please
```
node -v
v13.8.0

yarn -v
1.22.4

yarn info eslint | grep version:
version: '6.8.0'
```
> and have you made any edits to the template?
Only one change in `.prettierrc` after `npx preact-cli create typescript`: I set `tabWidth: 2`

**Comment by Akiyamka** [comment] 2020-05-07 07:42
According to [eslint documentation](https://eslint.org/docs/user-guide/command-line-interface#options) It must be something like
```
"lint": "eslint --ext js,jsx,ts,tsx src/"
```
```
yarn lint
yarn run v1.22.4
$ eslint --ext js,jsx,ts,tsx src/
Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.

/home/cherrytea/Git/shikardoors/src/components/app.tsx
  16:7   warning  'currentUrl' is assigned a value but never used  @typescript-eslint/no-unused-vars
  17:23  warning  Missing return type on function                  @typescript-eslint/explicit-function-return-type

/home/cherrytea/Git/shikardoors/src/routes/notfound/index.tsx
  9:25  error  `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`  react/no-unescaped-entities

/home/cherrytea/Git/shikardoors/src/routes/profile/index.tsx
  19:12  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type
  25:21  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type

✖ 5 problems (1 error, 4 warnings)
```

**Comment by RyanChristian4427** [comment] 2020-05-07 13:34
> 
> 
> According to [eslint documentation](https://eslint.org/docs/user-guide/command-line-interface#options) It must be something like
> 
> ```
> "lint": "eslint --ext js,jsx,ts,tsx src/"
> ```
> 
> This record work fine for me
> 
> ```
> yarn lint
> yarn run v1.22.4
> $ eslint --ext js,jsx,ts,tsx src/
> Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.
> /src/components/app.tsx
>   16:7   warning  'currentUrl' is assigned a value but never used  @typescript-eslint/no-unused-vars
>   17:23  warning  Missing return type on function                  @typescript-eslint/explicit-function-return-type
> 
> /src/routes/notfound/index.tsx
>   9:25  error  `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`  react/no-unescaped-entities
> 
> /src/routes/profile/index.tsx
>   19:12  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type
>   25:21  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type
> 
> ✖ 5 problems (1 error, 4 warnings)
> ```

No, what we have is valid. 

I remember seeing this issue, though I can't reproduce it locally. Would you be able to try replacing your eslint command with this please?

`"lint": "eslint 'src/**/*.{js,jsx,ts,tsx}'",`

If that works, I'll make a PR to get this fixed.

**Comment by ForsakenHarmony** [comment] 2020-05-07 13:47
Yeah, it might be shell expansion

**Comment by Akiyamka** [comment] 2020-05-07 16:33
@RyanChristian4427 you right, it's help!

**Comment by RyanChristian4427** [comment] 2020-05-07 16:35
Glad to hear it. I'll take the 'in-progress' status off the PR so that it can be merged in.

**Closed** 2021-08-30 09:46 UTC
